# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import os
import sys
import subprocess

from waflib import Options
from waflib.Errors import WafError

#def options(opt):
#    pass

def configure(conf):
    conf.env['ENABLE_ZMQ'] = conf.check(mandatory=False, lib='zmq', define_name='HAVE_ZMQ', uselib='ZMQ')
    conf.env['ENABLE_PROTOBUF'] = conf.check(mandatory=False, lib='protobuf', define_name='HAVE_PROTOBUF', uselib='PROTOBUF')

    # check if protoc is installed
    conf.env['ENABLE_PROTOC'] = False

    protoc_min_version = (3,0,0)
    protoc = conf.find_program('protoc', var='PROTOC')

    # Waf versions return either a path string or a one-element sequence.
    protoc_bin = protoc[0] if isinstance(protoc, (list, tuple)) else protoc
    try:
        raw = subprocess.check_output([protoc_bin, '--version'], stderr=subprocess.STDOUT)
        import re
        match = re.search(r'(\d+)\.(\d+)\.(\d+)', raw.decode('utf-8'))
        if match is None:
            raise ValueError('unrecognized protoc version: %r' % raw)
        protoc_version = tuple(map(int, match.groups()))
    except Exception as exc:
        conf.fatal('protoc version check failed: %s' % exc)
    conf.msg('Checking for protoc version', '.'.join(map(str, protoc_version)))
    if protoc_version < protoc_min_version:
        conf.fatal('protoc version must be at least 3.0.0')
    conf.env['ENABLE_PROTOC'] = True
    if not conf.env['ENABLE_ZMQ'] or not conf.env['ENABLE_PROTOBUF']:
        conf.env['MODULES_NOT_BUILT'].append('opengym')
        return
    conf.env.append_value('LINKFLAGS', ['-lzmq', '-lprotobuf'])
    conf.env.append_value('LIB', ['zmq', 'protobuf'])
    pbSrcDir = './src/opengym/model/'
    try:
        for out_flag, target in [('--cpp_out', pbSrcDir),
                                 ('--python_out', pbSrcDir + 'ns3gym/ns3gym/')]:
            subprocess.check_call([protoc_bin, '-I=' + pbSrcDir,
                                   out_flag + '=' + target, pbSrcDir + 'messages.proto'])
    except (OSError, subprocess.CalledProcessError) as exc:
        conf.fatal('Protobuf message generation failed: %s' % exc)
    conf.msg('Build ns3gym Protobuf messages', 'Done')


def build(bld):
    # Don't do anything for this module if click should not be built.
    if 'opengym' in bld.env['MODULES_NOT_BUILT']:
        return

    module = bld.create_ns3_module('opengym', ['core'])
    module.source = [
        'model/opengym_interface.cc',
        'model/messages.pb.cc',
        'model/container.cc',
        'model/conweave-routing-env.cc',
        'model/conweave-obs-manager.cc',
        'model/spaces.cc',
        'model/opengym_env.cc',
        'helper/opengym-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('opengym')
    module_test.source = [
        'test/opengym-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'opengym'
    headers.source = [
        'model/opengym_interface.h',
        'model/messages.pb.h',
        'model/container.h',
        'model/conweave-routing-env.h',
        'model/conweave-obs-manager.h',
        'model/spaces.h',
        'model/opengym_env.h',
        'helper/opengym-helper.h',
        ]

    if bld.env['ENABLE_ZMQ']:
        module.use.extend(['lzmq'])
        module.use.extend(['lprotobuf'])

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

